packages:
  - "v17"
  - "v18"

minimumReleaseAge: 10080
minimumReleaseAgeStrict: true
allowBuilds:
  core-js: true
  esbuild: true
  unrs-resolver: true
blockExoticSubdeps: true
overrides:
  dompurify@<=3.4.12: ^3.4.13
  js-yaml@<4.3.1: ^4.3.1
  nanoid@<3.3.18: ^3.3.18
minimumReleaseAgeExclude:
  - '@umbraco-cms/backoffice@17.6.2 || 18.1.1'
