//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Articulate.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ArticulateResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ArticulateResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Articulate.Resources.ArticulateResources", typeof(ArticulateResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;umbPackage&gt;
        ///  &lt;files&gt;
        ///    &lt;file&gt;
        ///      &lt;guid&gt;package.manifest&lt;/guid&gt;
        ///      &lt;orgPath&gt;~/App_Plugins/Articulate&lt;/orgPath&gt;
        ///      &lt;orgName&gt;package.manifest&lt;/orgName&gt;
        ///    &lt;/file&gt;
        ///    &lt;file&gt;
        ///      &lt;guid&gt;md-editor.css&lt;/guid&gt;
        ///      &lt;orgPath&gt;~/App_Plugins/Articulate/Assets&lt;/orgPath&gt;
        ///      &lt;orgName&gt;md-editor.css&lt;/orgName&gt;
        ///    &lt;/file&gt;
        ///    &lt;file&gt;
        ///      &lt;guid&gt;md-editor.js&lt;/guid&gt;
        ///      &lt;orgPath&gt;~/App_Plugins/Articulate/Assets&lt;/orgPath&gt;
        ///      &lt;orgName&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string packageManifest {
            get {
                return ResourceManager.GetString("packageManifest", resourceCulture);
            }
        }
    }
}
