// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteBlogmlImportFileData, DeleteBlogmlImportFileErrors, DeleteBlogmlImportFileResponses, GetBlogmlExportDisqusData, GetBlogmlExportDisqusErrors, GetBlogmlExportDisqusResponses, GetEditorsThemePickerThemesData, GetEditorsThemePickerThemesErrors, GetEditorsThemePickerThemesResponses, GetThemeDefaultData, GetThemeDefaultErrors, GetThemeDefaultResponses, PostBlogmlExportData, PostBlogmlExportErrors, PostBlogmlExportResponses, PostBlogmlImportData, PostBlogmlImportErrors, PostBlogmlImportFileData, PostBlogmlImportFileErrors, PostBlogmlImportFileResponses, PostBlogmlImportResponses, PostEditorsMarkdownPostData, PostEditorsMarkdownPostErrors, PostEditorsMarkdownPostResponses, PostThemeCopyData, PostThemeCopyErrors, PostThemeCopyResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class BlogMlService {
    /**
     * Exports blog data as a BlogML XML file.
     */
    public static postBlogmlExport<ThrowOnError extends boolean = false>(options?: Options<PostBlogmlExportData, ThrowOnError>) {
        return (options?.client ?? client).post<PostBlogmlExportResponses, PostBlogmlExportErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/articulate/api/v1/blogml/export',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Downloads the exported Disqus comment XML file.
     */
    public static getBlogmlExportDisqus<ThrowOnError extends boolean = false>(options?: Options<GetBlogmlExportDisqusData, ThrowOnError>) {
        return (options?.client ?? client).get<GetBlogmlExportDisqusResponses, GetBlogmlExportDisqusErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/articulate/api/v1/blogml/export/disqus',
            ...options
        });
    }
    
    /**
     * Imports blog data from a previously uploaded BlogML XML file.
     */
    public static postBlogmlImport<ThrowOnError extends boolean = false>(options?: Options<PostBlogmlImportData, ThrowOnError>) {
        return (options?.client ?? client).post<PostBlogmlImportResponses, PostBlogmlImportErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/articulate/api/v1/blogml/import',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Deletes a previously uploaded temporary BlogML import file.
     */
    public static deleteBlogmlImportFile<ThrowOnError extends boolean = false>(options?: Options<DeleteBlogmlImportFileData, ThrowOnError>) {
        return (options?.client ?? client).delete<DeleteBlogmlImportFileResponses, DeleteBlogmlImportFileErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/articulate/api/v1/blogml/import-file',
            ...options
        });
    }
    
    /**
     * Begins the BlogML import process by accepting an uploaded XML file.
     *
     * The name specified in the form's element or FormData must match the name of the parameter, e.g., <input type="file" name="importFile">
     */
    public static postBlogmlImportFile<ThrowOnError extends boolean = false>(options?: Options<PostBlogmlImportFileData, ThrowOnError>) {
        return (options?.client ?? client).post<PostBlogmlImportFileResponses, PostBlogmlImportFileErrors, ThrowOnError>({
            ...formDataBodySerializer,
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/articulate/api/v1/blogml/import-file',
            ...options,
            headers: {
                'Content-Type': null,
                ...options?.headers
            }
        });
    }
}

export class MarkdownEditorService {
    /**
     * Creates a new post under the specified Articulate node.
     */
    public static postEditorsMarkdownPost<ThrowOnError extends boolean = false>(options?: Options<PostEditorsMarkdownPostData, ThrowOnError>) {
        return (options?.client ?? client).post<PostEditorsMarkdownPostResponses, PostEditorsMarkdownPostErrors, ThrowOnError>({
            ...formDataBodySerializer,
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/articulate/api/v1/editors/markdown/post',
            ...options,
            headers: {
                'Content-Type': null,
                ...options?.headers
            }
        });
    }
}

export class ThemeOptionsService {
    /**
     * Copies a theme to a new theme name.
     */
    public static postThemeCopy<ThrowOnError extends boolean = false>(options?: Options<PostThemeCopyData, ThrowOnError>) {
        return (options?.client ?? client).post<PostThemeCopyResponses, PostThemeCopyErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/articulate/api/v1/theme/copy',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Retrieves the list of default Articulate themes.
     *
     * This endpoint returns the names of all default themes available in the system.
     */
    public static getThemeDefault<ThrowOnError extends boolean = false>(options?: Options<GetThemeDefaultData, ThrowOnError>) {
        return (options?.client ?? client).get<GetThemeDefaultResponses, GetThemeDefaultErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/articulate/api/v1/theme/default',
            ...options
        });
    }
}

export class ThemePickerService {
    /**
     * Gets the list of all available Articulate themes, both default and user-defined.
     *
     * This endpoint returns the names of all available themes, including both default and user-defined themes.
     */
    public static getEditorsThemePickerThemes<ThrowOnError extends boolean = false>(options?: Options<GetEditorsThemePickerThemesData, ThrowOnError>) {
        return (options?.client ?? client).get<GetEditorsThemePickerThemesResponses, GetEditorsThemePickerThemesErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/articulate/api/v1/editors/theme-picker/themes',
            ...options
        });
    }
}
