// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44366' | (string & {});
};

/**
 * Represents the response of creating a post.
 */
export type CreatePostResponse = {
    /**
     * The URL of the created post.
     */
    url: string;
};

/**
 * Represents the options for exporting blog data in BlogML format.
 */
export type ExportModel = {
    /**
     * Gets or sets the unique identifier of the Articulate node to export.
     */
    articulateBlogNode: string;
    /**
     * Gets or sets a value indicating whether the images should be exported as Base64 strings within the BlogML XML file.
     */
    exportImagesAsBase64: boolean;
};

/**
 * Represents the response model for the BlogML post initialization.
 */
export type ImportFileResponse = {
    /**
     * Gets or sets the temporary file name used to store the uploaded BlogML file.
     */
    temporaryFileName: string;
    /**
     * Gets or sets the number of posts detected in the BlogML file.
     */
    postCount: number;
    /**
     * Gets or sets the number of external image attachments referenced in the BlogML file.
     */
    externalImageCount: number;
    /**
     * Gets or sets the unique external hosts referenced by image attachments in the BlogML file.
     */
    externalHosts: Array<string>;
    /**
     * Gets or sets the external hosts referenced by the BlogML file that are not currently allowlisted.
     */
    blockedExternalHosts: Array<string>;
};

/**
 * Represents the options for importing blog data from a BlogML file.
 */
export type ImportModel = {
    /**
     * Gets or sets the unique identifier of the Articulate node to import into.
     */
    articulateBlogNode: string;
    /**
     * Gets or sets a value indicating whether to overwrite existing posts during import.
     */
    overwrite: boolean;
    /**
     * Gets or sets the regular expression pattern to match in post content during import.
     */
    regexMatch?: string | null;
    /**
     * Gets or sets the replacement string for the regular expression match in post content.
     */
    regexReplace?: string | null;
    /**
     * Gets or sets a value indicating whether to publish imported posts.
     */
    publish: boolean;
    /**
     * Gets or sets the temporary file name of the uploaded BlogML file.
     */
    tempFile: string;
    /**
     * Gets or sets a value indicating whether to export Disqus XML after import.
     */
    exportDisqusXml: boolean;
    /**
     * Gets or sets a value indicating whether to import the first image found in each post.
     */
    importFirstImage: boolean;
};

/**
 * Represents the result of a BlogML import with operation statistics.
 */
export type ImportResponse = {
    /**
     * Gets or sets the number of Posts that were imported.
     */
    postCount: number;
    /**
     * Gets or sets the number of Authors that were imported.
     */
    authorCount: number;
    /**
     * Gets or sets the number of comments that were written to the Disqus comments XML export file.
     */
    commentCount: number;
    /**
     * Gets or sets a value indicating whether the import completed successfully (true) or if it failed (false).
     */
    completed: boolean;
};

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    [key: string]: unknown;
};

/**
 * Represents the data required to copy an existing theme to a new theme name.
 * The new theme name must not contain any invalid file name characters.
 */
export type ThemeCopyModel = {
    /**
     * Gets or sets the name of the existing theme to copy.
     */
    themeName: string;
    /**
     * Gets or sets the new name for the copied theme.
     */
    newThemeName: string;
};

export type ValidationProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    errors: {
        [key: string]: Array<string>;
    };
    [key: string]: unknown;
};

export type PostBlogmlExportData = {
    /**
     * Represents the options for exporting blog data in BlogML format.
     */
    body?: ExportModel;
    path?: never;
    query?: never;
    url: '/umbraco/articulate/api/v1/blogml/export';
};

export type PostBlogmlExportErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Export failed due to a server error.
     */
    500: ProblemDetails;
    /**
     * The service is unavailable or the blog node is invalid.
     */
    503: ProblemDetails;
};

export type PostBlogmlExportError = PostBlogmlExportErrors[keyof PostBlogmlExportErrors];

export type PostBlogmlExportResponses = {
    /**
     * Returns the BlogML XML file as a downloadable stream.
     */
    200: Blob | File;
};

export type PostBlogmlExportResponse = PostBlogmlExportResponses[keyof PostBlogmlExportResponses];

export type GetBlogmlExportDisqusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/articulate/api/v1/blogml/export/disqus';
};

export type GetBlogmlExportDisqusErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * The Disqus XML export file could not be found.
     */
    404: ProblemDetails;
};

export type GetBlogmlExportDisqusError = GetBlogmlExportDisqusErrors[keyof GetBlogmlExportDisqusErrors];

export type GetBlogmlExportDisqusResponses = {
    /**
     * Returns the Disqus comment XML file as a downloadable stream.
     */
    200: Blob | File;
};

export type GetBlogmlExportDisqusResponse = GetBlogmlExportDisqusResponses[keyof GetBlogmlExportDisqusResponses];

export type PostBlogmlImportData = {
    /**
     * Represents the options for importing blog data from a BlogML file.
     */
    body?: ImportModel;
    path?: never;
    query?: never;
    url: '/umbraco/articulate/api/v1/blogml/import';
};

export type PostBlogmlImportErrors = {
    /**
     * The requested Articulate node ID could not be found or is not a valid Articulate node.
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * The requested temporary file could not be found.
     */
    404: ProblemDetails;
    /**
     * Import failed due to a server error.
     */
    500: ProblemDetails;
};

export type PostBlogmlImportError = PostBlogmlImportErrors[keyof PostBlogmlImportErrors];

export type PostBlogmlImportResponses = {
    /**
     * Represents the result of a BlogML import with operation statistics.
     */
    200: ImportResponse;
};

export type PostBlogmlImportResponse = PostBlogmlImportResponses[keyof PostBlogmlImportResponses];

export type DeleteBlogmlImportFileData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * The temporary file name returned by the import-file endpoint.
         */
        tempFile?: string;
    };
    url: '/umbraco/articulate/api/v1/blogml/import-file';
};

export type DeleteBlogmlImportFileErrors = {
    /**
     * The temporary file name is invalid.
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type DeleteBlogmlImportFileError = DeleteBlogmlImportFileErrors[keyof DeleteBlogmlImportFileErrors];

export type DeleteBlogmlImportFileResponses = {
    /**
     * The temporary file was deleted or did not exist.
     */
    204: void;
};

export type DeleteBlogmlImportFileResponse = DeleteBlogmlImportFileResponses[keyof DeleteBlogmlImportFileResponses];

export type PostBlogmlImportFileData = {
    body?: {
        /**
         * The file to import, must be an XML file in BlogML format.
         */
        importFile?: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/umbraco/articulate/api/v1/blogml/import-file';
};

export type PostBlogmlImportFileErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * The request is not a valid form file, file is missing, or the file is not XML.
     */
    415: ProblemDetails;
    /**
     * Upload failed due to a server error.
     */
    500: ProblemDetails;
};

export type PostBlogmlImportFileError = PostBlogmlImportFileErrors[keyof PostBlogmlImportFileErrors];

export type PostBlogmlImportFileResponses = {
    /**
     * Represents the response model for the BlogML post initialization.
     */
    200: ImportFileResponse;
};

export type PostBlogmlImportFileResponse = PostBlogmlImportFileResponses[keyof PostBlogmlImportFileResponses];

export type PostEditorsMarkdownPostData = {
    body?: {
        /**
         * The JSON model containing the post data: Title, Body, Slug, Excerpt, Tags, Categories,
         * ArticulateBlogNode, and whether the first image should be extracted as a dedicated property.
         */
        json?: string;
    };
    path?: never;
    query?: never;
    url: '/umbraco/articulate/api/v1/editors/markdown/post';
};

export type PostEditorsMarkdownPostErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Unprocessable Content
     */
    422: ValidationProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PostEditorsMarkdownPostError = PostEditorsMarkdownPostErrors[keyof PostEditorsMarkdownPostErrors];

export type PostEditorsMarkdownPostResponses = {
    /**
     * Represents the response of creating a post.
     */
    200: CreatePostResponse;
};

export type PostEditorsMarkdownPostResponse = PostEditorsMarkdownPostResponses[keyof PostEditorsMarkdownPostResponses];

export type PostThemeCopyData = {
    /**
     * Represents the data required to copy an existing theme to a new theme name.
     * The new theme name must not contain any invalid file name characters.
     */
    body?: ThemeCopyModel;
    path?: never;
    query?: never;
    url: '/umbraco/articulate/api/v1/theme/copy';
};

export type PostThemeCopyErrors = {
    /**
     * The destination theme name matches a built-in theme.
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * The theme name specified in the model does not exist.
     */
    404: ProblemDetails;
    /**
     * The new theme name specified in the model already exists.
     */
    409: ProblemDetails;
    /**
     * An unexpected error occurred during the theme copy operation.
     */
    500: ProblemDetails;
};

export type PostThemeCopyError = PostThemeCopyErrors[keyof PostThemeCopyErrors];

export type PostThemeCopyResponses = {
    /**
     * The theme was successfully copied to the new theme name.
     */
    200: string;
};

export type PostThemeCopyResponse = PostThemeCopyResponses[keyof PostThemeCopyResponses];

export type GetThemeDefaultData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/articulate/api/v1/theme/default';
};

export type GetThemeDefaultErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * An unexpected error occurred while retrieving default themes.
     */
    500: ProblemDetails;
};

export type GetThemeDefaultError = GetThemeDefaultErrors[keyof GetThemeDefaultErrors];

export type GetThemeDefaultResponses = {
    /**
     * Returns the list of default theme names.
     */
    200: Array<string>;
};

export type GetThemeDefaultResponse = GetThemeDefaultResponses[keyof GetThemeDefaultResponses];

export type GetEditorsThemePickerThemesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/articulate/api/v1/editors/theme-picker/themes';
};

export type GetEditorsThemePickerThemesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetEditorsThemePickerThemesError = GetEditorsThemePickerThemesErrors[keyof GetEditorsThemePickerThemesErrors];

export type GetEditorsThemePickerThemesResponses = {
    /**
     * Returns the list of all available theme names.
     */
    200: Array<string>;
};

export type GetEditorsThemePickerThemesResponse = GetEditorsThemePickerThemesResponses[keyof GetEditorsThemePickerThemesResponses];
