// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44366/' | (string & {});
};

export type CreatePostResponse = {
    url: string;
};

export type EntityTagHeaderValue = {
    tag: StringSegment;
    isWeak: boolean;
};

export type ExportModel = {
    articulateBlogNode: string;
    exportImagesAsBase64: boolean;
};

export type FileContentResult = {
    fileContents: string;
    contentType: null | string;
    fileDownloadName: null | string;
    lastModified?: null | string;
    entityTag?: null | EntityTagHeaderValue;
    enableRangeProcessing: boolean;
};

export type IFormFile = Blob | File;

export type ImportFileResponse = {
    temporaryFileName: string;
    postCount: number | string;
    externalImageCount: number | string;
    externalHosts: Array<string>;
    blockedExternalHosts: Array<string>;
};

export type ImportModel = {
    articulateBlogNode: string;
    overwrite: boolean;
    regexMatch?: null | string;
    regexReplace?: null | string;
    publish: boolean;
    tempFile: string;
    exportDisqusXml: boolean;
    importFirstImage: boolean;
};

export type ImportResponse = {
    postCount: number | string;
    authorCount: number | string;
    commentCount: number | string;
    completed: boolean;
};

export type ProblemDetails = {
    type?: null | string;
    title?: null | string;
    status?: null | number | string;
    detail?: null | string;
    instance?: null | string;
};

export type StringSegment = {
    buffer?: null | string;
    offset: number | string;
    length: number | string;
    value?: null | string;
    hasValue: boolean;
};

export type ThemeCopyModel = {
    themeName: string;
    newThemeName: string;
};

export type ValidationProblemDetails = {
    type?: null | string;
    title?: null | string;
    status?: null | number | string;
    detail?: null | string;
    instance?: null | string;
    errors: {
        [key: string]: Array<string>;
    };
};

export type PostBlogmlExportData = {
    body: ExportModel;
    path?: never;
    query?: never;
    url: '/umbraco/articulate/api/v1/blogml/export';
};

export type PostBlogmlExportErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
    /**
     * Service Unavailable
     */
    503: ProblemDetails;
};

export type PostBlogmlExportError = PostBlogmlExportErrors[keyof PostBlogmlExportErrors];

export type PostBlogmlExportResponses = {
    /**
     * OK
     */
    200: FileContentResult;
};

export type PostBlogmlExportResponse = PostBlogmlExportResponses[keyof PostBlogmlExportResponses];

export type GetBlogmlExportDisqusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/articulate/api/v1/blogml/export/disqus';
};

export type GetBlogmlExportDisqusErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetBlogmlExportDisqusError = GetBlogmlExportDisqusErrors[keyof GetBlogmlExportDisqusErrors];

export type GetBlogmlExportDisqusResponses = {
    /**
     * OK
     */
    200: FileContentResult;
};

export type GetBlogmlExportDisqusResponse = GetBlogmlExportDisqusResponses[keyof GetBlogmlExportDisqusResponses];

export type PostBlogmlImportData = {
    body: ImportModel;
    path?: never;
    query?: never;
    url: '/umbraco/articulate/api/v1/blogml/import';
};

export type PostBlogmlImportErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PostBlogmlImportError = PostBlogmlImportErrors[keyof PostBlogmlImportErrors];

export type PostBlogmlImportResponses = {
    /**
     * OK
     */
    200: ImportResponse;
};

export type PostBlogmlImportResponse = PostBlogmlImportResponses[keyof PostBlogmlImportResponses];

export type DeleteBlogmlImportFileData = {
    body?: never;
    path?: never;
    query?: {
        tempFile?: string;
    };
    url: '/umbraco/articulate/api/v1/blogml/import-file';
};

export type DeleteBlogmlImportFileErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type DeleteBlogmlImportFileError = DeleteBlogmlImportFileErrors[keyof DeleteBlogmlImportFileErrors];

export type DeleteBlogmlImportFileResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteBlogmlImportFileResponse = DeleteBlogmlImportFileResponses[keyof DeleteBlogmlImportFileResponses];

export type PostBlogmlImportFileData = {
    body: {
        importFile?: IFormFile;
    };
    path?: never;
    query?: never;
    url: '/umbraco/articulate/api/v1/blogml/import-file';
};

export type PostBlogmlImportFileErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Unsupported Media Type
     */
    415: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PostBlogmlImportFileError = PostBlogmlImportFileErrors[keyof PostBlogmlImportFileErrors];

export type PostBlogmlImportFileResponses = {
    /**
     * OK
     */
    200: ImportFileResponse;
};

export type PostBlogmlImportFileResponse = PostBlogmlImportFileResponses[keyof PostBlogmlImportFileResponses];

export type PostEditorsMarkdownPostData = {
    body: {
        json?: string;
    };
    path?: never;
    query?: never;
    url: '/umbraco/articulate/api/v1/editors/markdown/post';
};

export type PostEditorsMarkdownPostErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Unprocessable Entity
     */
    422: ValidationProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PostEditorsMarkdownPostError = PostEditorsMarkdownPostErrors[keyof PostEditorsMarkdownPostErrors];

export type PostEditorsMarkdownPostResponses = {
    /**
     * OK
     */
    200: CreatePostResponse;
};

export type PostEditorsMarkdownPostResponse = PostEditorsMarkdownPostResponses[keyof PostEditorsMarkdownPostResponses];

export type PostThemeCopyData = {
    body: ThemeCopyModel;
    path?: never;
    query?: never;
    url: '/umbraco/articulate/api/v1/theme/copy';
};

export type PostThemeCopyErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PostThemeCopyError = PostThemeCopyErrors[keyof PostThemeCopyErrors];

export type PostThemeCopyResponses = {
    /**
     * OK
     */
    200: string;
};

export type PostThemeCopyResponse = PostThemeCopyResponses[keyof PostThemeCopyResponses];

export type GetThemeDefaultData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/articulate/api/v1/theme/default';
};

export type GetThemeDefaultErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetThemeDefaultError = GetThemeDefaultErrors[keyof GetThemeDefaultErrors];

export type GetThemeDefaultResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type GetThemeDefaultResponse = GetThemeDefaultResponses[keyof GetThemeDefaultResponses];

export type GetEditorsThemePickerThemesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/articulate/api/v1/editors/theme-picker/themes';
};

export type GetEditorsThemePickerThemesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetEditorsThemePickerThemesError = GetEditorsThemePickerThemesErrors[keyof GetEditorsThemePickerThemesErrors];

export type GetEditorsThemePickerThemesResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type GetEditorsThemePickerThemesResponse = GetEditorsThemePickerThemesResponses[keyof GetEditorsThemePickerThemesResponses];
